name: React CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Linting
        run: npm run lint
      - name: Tests
        run: 'npm run ci:test'
  cd:
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main'
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Merge to main
        run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git fetch origin ${{ github.event.pull_request.head.ref }}
        git checkout main
        git merge --no-ff FETCH_HEAD -m "Merge pull request #${{ github.event.pull_request.number }}"
        git push origin main